In [5]:
import pandas
from collections import Counter

In [6]:
df = pandas.read_csv('edited500.csv')
df

,PMID,Index,Candidates,Coordinates,Sentence,Place_or_no,Correct_or_no,Type,Sub_type,Notes,Other Notes
0,10552319,3,"Quebec, QC, Canada","-71.219,46.813","According to the Quebec Classification System,...",n,n,method name,method name,classification system name,NaN
1,8934954,2,"Wells, Somerset, UK|Wells, ME, USA","-2.648,51.209|-70.591,43.322",Although his life ended tragically in 1848--an...,n,n,people name,people name,NaN,NaN
2,11591130,7,"Homer, LA, USA|Homer, AK, USA","-93.056,32.792|-151.546,59.645",Neither Homer altered the agonist profiles of ...,n,n,biological term,protein name,NaN,NaN
3,23167678,3,"Basel, Switzerland","7.581,47.56",The hypothesis of this study was that low-curr...,y,y,correct placename,correct placename,NaN,NaN
4,6143329,3,Serbia|Montenegro,-|-,Norepinephrine levels were elevated in SCG and...,n,n,acronym,animal name,"superior cervical ganglion (SCG), and Spontane...",Srbija i Crna GoraÂ (SCG)
5,15001970,12,UK|USA,-|-,Clinically relevant interactions with other dr...,n,n,biological term,biological term,"St John's wort, an extract of the medicinal pl...",NaN
6,26131722,5,"Melbourne, VIC, Australia","144.963,-37.814",We developed a continuous-time structured HMM ...,y,y,correct placename,correct placename,NaN,NaN
7,10216372,1,"Krakow, Poland","19.96,50.06",The aim of the study was to evaluate the relat...,y,y,correct placename,correct placename,NaN,"Poland, Polska"
8,19841337,1,"San Diego, CA, USA","-117.162,32.716",To quantify the safety and efficiency of Postg...,y,y,correct placename,correct placename,NaN,NaN
9,21665017,10,"Shanghai, China","121.47,31.23",This is the first study to investigate the exp...,y,y,correct placename,correct placename,NaN,NaN
10,12347136,16,Armenia|Russia|Latvia|Uzbekistan|Estonia|Lithu...,-|-|-|-|-|-|-|-|-|-|-|-|-|-,These changes occurred during the mid-1980s an...,y,y,partial correct,has 1 got n,NaN,Soviet Union
11,26143942,2,"Benin City, Edo State, Nigeria","5.627,6.335","Article chosen Chamberlain JM, Okada P, Holsti...",n,n,reference,reference,people name,or method
12,10095331,1,"Travis AFB, Fairfield, CA, USA","-121.939,38.268",There is growing evidence that corrective inpu...,n,n,reference,reference,people name,NaN
13,23703441,4,Italy|USA,-|-,The aim of this study was to breed the sandfli...,y,n,wrong place,wrong place,NaN,should be Iran
14,21707139,4,Germany|Japan|USA,-|-|-,We compared the results for two genetically di...,n,n,animal name,stains name,NaN,NaN
15,10559668,7,"Basel, Switzerland","7.581,47.56","Copyrightz1999S.KargerAG,Basel",n,n,reference,reference,copyright,NaN
16,16504732,1,"ACT, Australia","149.124,-35.308",Autologous chondrocyte transplantation (ACT) h...,n,n,acronym,method name,NaN,NaN
17,19731262,14,"Flint, MI, USA","-83.686,43.011",We illustrate our methodology by analyzing dat...,n,n,study name,study name,NaN,NaN
18,2646919,1,"Lima, Peru","-77.046,-12.093",Community-based studies of diarrhea etiology a...,y,y,correct placename,correct placename,NaN,NaN
19,11603623,1,"Sicilia, Italy","13.789,37.152",From epidemiological data obtained over more t...,y,y,correct placename,correct placename,NaN,NaN
20,18197255,2,Saudi Arabia|USA,-|-,A national survey was conducted in all public ...,y,n,wrong place,wrong place,NaN,Malawi
21,6365548,12,"Paris, France","2.351,48.857","(1976) Biochimie (Paris) 58, 305--316; Ghrir, ...",n,n,reference,reference,NaN,NaN
22,1425964,4,"VIC, Australia","145.469,-36.559","At 1-100 nM, ET-1, ET-2 and VIC were equipoten...",n,n,acronym,biological term,NaN,"vasoactive intestinal contractor, VIC can be V..."
23,2564242,8,"Hassall, Cheshire, UK","-2.356,53.114",Scattered staining with these antibodies was i...,n,n,biological term,cell name,NaN,NaN
24,1435133,5,"Falun, Sweden|Stockholm, Sweden","15.632,60.602|18.064,59.333",Forty-one per cent of the patients in Falun an...,y,y,correct placename,correct placename,NaN,NaN
25,11640084,1,"Rovigo, Veneto, Italy","11.79,45.071","Minadois was born in Rovigo, son of a physicia...",y,y,correct placename,correct placename,NaN,NaN
26,19641300,5,"Philadelphia, PA, USA","-75.162,39.952",One patient was Philadelphia chromosome positi...,n,n,biological term,chromosome name,NaN,NaN
27,23468229,8,"Spain|GU, USA",-|-,TTV2Hn93 strain was classified into subtype TT...,n,n,biological term,strain name,NaN,NaN
28,14755451,7,Italy|USA,-|-,The present study indicates that the IDE gene ...,n,n,acronym,enzyme name,NaN,"insulin degrading enzyme(IDE), Japan"
29,6657512,7,"Argo, IL, USA","-90.018,42.004",Argo-Met-enkephalin inhibited enkephalin break...,n,n,biological term,biological term,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
470,18095647,14,"MA, USA|NY, USA",-|-,German and Mesten of O. basilicum increased wi...,n,n,material name,material name,NaN,NaN
471,1529733,2,"Nagasaki, Japan","129.88,32.75",Social features of residents in 259 areas in t...,y,y,correct placename,correct placename,NaN,NaN
472,10559650,2,"Campania, Italy","14.784,40.749","Moreover, the cognitive status may be impaired...",y,y,correct placename,correct placename,NaN,NaN
473,1424541,1,"Washington, DC, USA","-77.032,38.89",The purpose of this study was to examine chang...,n,n,nationality,nationality,NaN,NaN
474,1189909,1,"Newcastle, ME, USA|Newcastle Upon Tyne, Tyne a...","-69.536,44.035|-1.613,54.978",A second survey of age at menarche in north-ea...,y,y,correct placename,correct placename,NaN,NaN
475,23500090,1,"Obama, Fukui, Japan","135.74,35.5",The Patient Protection and Affordable Care Act...,n,n,General English name,General English name,NaN,NaN
476,23087540,11,"Lublin, Poland","22.57,51.24",Statistical analysis shows that minimum temper...,y,y,correct placename,correct placename,NaN,NaN
477,16495008,4,"Tampa, FL, USA","-82.459,27.947",Goals of this study were to validate the predi...,n,n,method name,assessment name,NaN,NaN
478,14987179,4,"Oxford, GA, USA","-83.867,33.616",A definition is proposed based on the Oxford E...,n,n,method name,dictionary name,NaN,NaN
479,11709730,4,"Frankfurt am Main, Germany","8.681,50.112",In the following study we screened for immunit...,y,y,correct placename,correct placename,NaN,NaN
480,8699003,2,"Hudson, OH, USA|Hudson, NY, USA|Hudson, FL, US...","-81.44,41.243|-73.791,42.253|-82.695,28.364|-7...",In order to determine if the IAH was a reliabl...,y,n,wrong placename,wrong placename,should be Australia,Got general English name
481,1528912,1,"Edmonton, AB, Canada","-113.49,53.546",Hispid cotton rats were inoculated intranasall...,n,n,biological term,virus name,NaN,NaN
482,24491575,10,"Shiga, Japan","135.92,35.19",PKC recruitment was independent of the intimin...,n,n,biological term,toxin name,NaN,Shiga toxins
483,6141229,5,Montenegro|Serbia,-|-,This impression was supported by examining neu...,n,n,acronym,biological term,NaN,superior cervical ganglion
484,10529627,1,Brazil|China|France|Italy,-|-|-|-,Lipoprotein glomerulopathy (LPG) is a newly re...,n,n,acronym,disease name,NaN,NaN
485,22885492,6,"Shanghai, China","121.47,31.23",There was no significant difference between ma...,y,y,correct placename,correct placename,NaN,NaN
486,21595950,3,"Oxford, MD, USA","-76.172,38.688",We hypothesized that subjective instability an...,n,n,method name,assessment name,NaN,NaN
487,16512605,3,"Astrakhan, Astrakhanskaya, Russia","48.083,46.367",Comparative analysis of molecular genetic mark...,n,n,biological term,strain name,NaN,NaN
488,6691528,1,"Columbia, MD, USA","-76.867,39.209","We followed a cohort of 7,666 individuals enro...",y,y,correct placename,correct placename,NaN,NaN
489,3078349,1,"Recife, Pernambuco, Brazil","-34.881,-8.054",326 samples of diarrheal feces obtained from c...,y,y,correct placename,correct placename,NaN,NaN
490,10552886,1,"MS, USA|Mato Grosso do Sul, Brazil|Australia","-|-54.545,-20.618|-",Sixteen species (44 samples) of marine polycha...,y,y,partially correct,has 1 got n,NaN,NaN
491,23681348,4,Hungary|India|Japan,-|-|-,Trustworthiness of the study was evaluated usi...,n,n,acronym,disease name,NaN,Chronic kidney disease (CKD)
492,17957761,4,"Haryana, India","76.12,29.245",Ahirs and Jats of Haryana (India).,y,y,correct placename,correct placename,NaN,NaN
493,18184814,8,UK|USA,-|-,Empirical estimates show that introduction of ...,y,n,wrong placename,wrong placename,should be Mexico,NaN
494,22878938,6,"New Hope, MN, USA|New Hope, PA, USA","-93.402,45.037|-74.952,40.366",Results indicate that parental perceptions of ...,n,n,project name,project name,NaN,NaN
495,17927795,2,"Cambridge, Cambridgeshire, UK","0.131,52.203",In addition to conventional surgical technique...,y,y,correct placename,correct placename,NaN,NaN
496,1526785,2,"Monte-Carlo, Monaco, Monaco","7.426,43.74",Upper and lower bounds on doses are based on M...,n,n,method name,calculation name,NaN,NaN
497,12344073,5,"Accord, NY, USA","-74.231,41.787",Appended to the Accord are operative rules rel...,n,n,method name,accord name,NaN,NaN
498,1426409,1,"Lindau, Zurich, Switzerland|Lindau, Germany","8.672,47.442|9.707,47.557",A definite association between Von Hippel-Lind...,n,n,biological term,dictionary name,NaN,NaN
499,1183256,4,"Melbourne, AR, USA|Melbourne, FL, USA","-91.906,36.059|-80.607,28.079",The greater number of ependymomas in Melbourne...,y,y,correct placename,correct placename,NaN,NaN

In [8]:
Counter(df['Sub_type'])

Counter({'method name': 17,
         'people name': 11,
         'protein name': 4,
         'correct placename': 196,
         'animal name': 13,
         'biological term': 42,
         'has 1 got n': 7,
         'reference': 22,
         'wrong place': 4,
         'stains name': 1,
         'study name': 3,
         'cell name': 3,
         'chromosome name': 1,
         'strain name': 6,
         'enzyme name': 1,
         'survey name': 1,
         'orgnization name': 2,
         'materials name': 1,
         'author name': 1,
         'dataset name': 1,
         'testing method name': 7,
         'chemical name': 1,
         'disease name': 21,
         'questionnaire name': 1,
         'search method name': 1,
         'procedure method name': 1,
         'has n got 1': 8,
         'people': 1,
         'reaction name': 1,
         'unknown': 3,
         'method': 1,
         'bacteria name': 1,
         'brand name': 1,
         'testing method': 2,
         'insurance name': 1,
         'wrong placename': 37,
         'soil name': 1,
         'has 1 got 2': 1,
         nan: 1,
         'has 2 got 1': 2,
         'has n got 2': 1,
         'has 3 got 1': 1,
         'law name': 1,
         'algorithm name': 1,
         'association name': 2,
         'ognization name': 1,
         'procedure name': 1,
         'conference name': 1,
         'assessment method': 2,
         'analysis method': 1,
         'therapy name': 1,
         'toxin name': 2,
         'general English word': 1,
         'simulation method': 2,
         'company name': 1,
         'ac': 1,
         'group name': 1,
         'structure name': 1,
         'cement name': 1,
         'rule name': 1,
         'too specific': 1,
         'texture name': 1,
         'general english word': 1,
         'smear method': 1,
         'assessment name': 4,
         'rating system': 3,
         'extraction method': 1,
         'index name': 1,
         'scale name': 2,
         'acronym': 6,
         'organization name': 2,
         'filter name': 1,
         'series name': 1,
         'guideline name': 1,
         'model name': 1,
         'simulation name': 1,
         'Encyclopedia name': 1,
         'population name': 1,
         'model system name': 1,
         'surgery name': 1,
         'copyright': 1,
         'mutant name': 1,
         'grant name': 1,
         'newspaper': 1,
         'rating scale name': 1,
         'material name': 1,
         'nationality': 1,
         'General English name': 1,
         'dictionary name': 2,
         'virus name': 1,
         'project name': 1,
         'calculation name': 1,
         'accord name': 1})